/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ProjectsCropheatAiRouteImport } from './routes/projects.cropheat-ai'
import { Route as ProjectsEdupredictRouteImport } from './routes/projects.edupredict'
import { Route as ProjectsElectricityRouteImport } from './routes/projects.electricity'
import { Route as ProjectsPlantscanRouteImport } from './routes/projects.plantscan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCropheatAiRoute = ProjectsCropheatAiRouteImport.update({
  id: '/projects/cropheat-ai',
  path: '/projects/cropheat-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsEdupredictRoute = ProjectsEdupredictRouteImport.update({
  id: '/projects/edupredict',
  path: '/projects/edupredict',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsElectricityRoute = ProjectsElectricityRouteImport.update({
  id: '/projects/electricity',
  path: '/projects/electricity',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsPlantscanRoute = ProjectsPlantscanRouteImport.update({
  id: '/projects/plantscan',
  path: '/projects/plantscan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/cropheat-ai': typeof ProjectsCropheatAiRoute
  '/projects/edupredict': typeof ProjectsEdupredictRoute
  '/projects/electricity': typeof ProjectsElectricityRoute
  '/projects/plantscan': typeof ProjectsPlantscanRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/cropheat-ai': typeof ProjectsCropheatAiRoute
  '/projects/edupredict': typeof ProjectsEdupredictRoute
  '/projects/electricity': typeof ProjectsElectricityRoute
  '/projects/plantscan': typeof ProjectsPlantscanRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/cropheat-ai': typeof ProjectsCropheatAiRoute
  '/projects/edupredict': typeof ProjectsEdupredictRoute
  '/projects/electricity': typeof ProjectsElectricityRoute
  '/projects/plantscan': typeof ProjectsPlantscanRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/projects/cropheat-ai'
    | '/projects/edupredict'
    | '/projects/electricity'
    | '/projects/plantscan'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/projects/cropheat-ai'
    | '/projects/edupredict'
    | '/projects/electricity'
    | '/projects/plantscan'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/projects/cropheat-ai'
    | '/projects/edupredict'
    | '/projects/electricity'
    | '/projects/plantscan'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProjectsCropheatAiRoute: typeof ProjectsCropheatAiRoute
  ProjectsEdupredictRoute: typeof ProjectsEdupredictRoute
  ProjectsElectricityRoute: typeof ProjectsElectricityRoute
  ProjectsPlantscanRoute: typeof ProjectsPlantscanRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/cropheat-ai': {
      id: '/projects/cropheat-ai'
      path: '/projects/cropheat-ai'
      fullPath: '/projects/cropheat-ai'
      preLoaderRoute: typeof ProjectsCropheatAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/edupredict': {
      id: '/projects/edupredict'
      path: '/projects/edupredict'
      fullPath: '/projects/edupredict'
      preLoaderRoute: typeof ProjectsEdupredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/electricity': {
      id: '/projects/electricity'
      path: '/projects/electricity'
      fullPath: '/projects/electricity'
      preLoaderRoute: typeof ProjectsElectricityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/plantscan': {
      id: '/projects/plantscan'
      path: '/projects/plantscan'
      fullPath: '/projects/plantscan'
      preLoaderRoute: typeof ProjectsPlantscanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProjectsCropheatAiRoute: ProjectsCropheatAiRoute,
  ProjectsEdupredictRoute: ProjectsEdupredictRoute,
  ProjectsElectricityRoute: ProjectsElectricityRoute,
  ProjectsPlantscanRoute: ProjectsPlantscanRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
